class WHITE_TIGER_HANGAR_ALIASES(object):
    WHITE_TIGER_TANK_CAROUSEL = 'whiteTigerTankCarousel'
    WHITE_TIGER_PRIME_TIME = 'whiteTigerPrimeTime.swf'
    WHITE_TIGER_PRIME_TIME_ALIAS = 'whiteTigerPrimeTime'
    WHITE_TIGER_PROGRESSION = 'whiteTigerProgression'
    WHITE_TIGER_HANGAR = 'whiteTigerHangarMode'
    WHITE_TIGER_WELCOME = 'whiteTigerWelcome'
    WHITE_TIGER_SETTINGS_WINDOW = 'whiteTigerSettingsWindow'
    WHITE_TIGER_QUEUE_SCREEN = 'whiteTigerQueueScreen'
    WHITE_TIGER_BATTLE_RESULT = 'whiteTigerBattleResult'
