class MECHANIC_WIDGET_DEVICES_CONST(object):
    DEVICE_STATE_CRITICAL = 'critical'
    DEVICE_STATE_DESTROYED = 'destroyed'
    DEVICE_NONE = 'None'
    DEVICE_CHASSIS = 'chassis'
    DEVICE_ENGINE = 'engine'
    DEVICE_AMMO_BAY = 'ammoBay'
    DEVICES = [DEVICE_NONE,
     DEVICE_CHASSIS,
     DEVICE_ENGINE,
     DEVICE_AMMO_BAY]
    LINKAGE_DEVICE_CRITICAL = 'DeviceCriticalUI'
    LINKAGE_DEVICE_DESTROYED = 'DeviceDestroyedUI'
