class SHELL_CALIBRATION_WIDGET_CONSTS(object):
    NO_BONUS = 'noBonus'
    DAMAGE_BONUS = 'damageBonus'
    PENETRATION_BONUS = 'penetrationBonus'
    SHELL_CALIBRATION_WIDGET_STATES = [NO_BONUS, DAMAGE_BONUS, PENETRATION_BONUS]
