package net.wg.last_stand.gui.battle.views.ribbonsPanel
{
   import net.wg.data.constants.generated.BATTLEATLAS;
   import net.wg.gui.components.ribbon.constants.RibbonColors;
   import net.wg.gui.components.ribbon.data.DamageSourceSetting;
   import net.wg.gui.components.ribbon.data.RibbonSettingByType;
   import net.wg.gui.components.ribbon.data.RibbonSettings;
   import net.wg.last_stand.data.constants.generated.LS_BATTLE_EFFICIENCY_TYPES;
   import net.wg.last_stand.data.constants.generated.LS_DAMAGE_SOURCE_TYPES;
   
   public class LSRibbonSettings extends RibbonSettings
   {
      
      public function LSRibbonSettings(param1:String, param2:String)
      {
         super(param1,param2);
      }
      
      override protected function atlasInit() : void
      {
         super.atlasInit();
         var _loc1_:String = RibbonColors.GREEN;
         var _loc2_:String = RibbonColors.ORANGE;
         var _loc3_:String = RibbonColors.RED;
         var _loc4_:String = RibbonColors.PURPLE;
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_REPAIR] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_REPAIR,_loc1_,BATTLEATLAS.RIBBONS_REPAIR,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_REPAIR_OTHER] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_REPAIR,_loc1_,BATTLEATLAS.RIBBONS_REPAIR,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_REPAIR_BY_OTHER] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_REPAIR,_loc1_,BATTLEATLAS.RIBBONS_REPAIR,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_DMG_VAMPIRE] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_DAMAGE,_loc1_,BATTLEATLAS.RIBBONS_DAMAGE,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_AOE_BURN] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_BURN,_loc1_,BATTLEATLAS.RIBBONS_BURN,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_AOE_DAMAGE] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_DAMAGE,_loc1_,BATTLEATLAS.RIBBONS_DAMAGE,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_SHOT_AOE_DAMAGE] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_DAMAGE,_loc1_,BATTLEATLAS.RIBBONS_DAMAGE,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_SHOT_AOE_DRAIN_ENEMY_HP] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_DAMAGE,_loc1_,BATTLEATLAS.RIBBONS_DAMAGE,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_SHOT_AOE_STUN] = new RibbonSettingByType(_loc1_,BATTLEATLAS.RIBBONS_DAMAGE,_loc1_,BATTLEATLAS.RIBBONS_DAMAGE,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_MODULES_DAMAGE_BLOCKED] = new RibbonSettingByType(_loc2_,BATTLEATLAS.LS_CRIT_DEFENCE,_loc2_,BATTLEATLAS.LS_CRIT_DEFENCE,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_PASSIVE_IGNITE] = new RibbonSettingByType(_loc2_,BATTLEATLAS.LS_BULLET_IGNITE,_loc2_,BATTLEATLAS.LS_BULLET_IGNITE,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_PASSIVE_VAMPIRE] = new RibbonSettingByType(_loc2_,BATTLEATLAS.LS_BULLET_VAMPIRE,_loc2_,BATTLEATLAS.LS_BULLET_VAMPIRE,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_BOMBER_EXPLOSION] = new RibbonSettingByType(_loc3_,BATTLEATLAS.RIBBONS_DAMAGE_ENEMY,_loc4_,BATTLEATLAS.RIBBONS_DAMAGE_ENEMY_BLIND,1);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_DMG_VAMPIRE_RECEIVED] = new RibbonSettingByType(_loc3_,BATTLEATLAS.RIBBONS_DAMAGE_ENEMY,_loc4_,BATTLEATLAS.RIBBONS_DAMAGE_ENEMY_BLIND,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_AOE_DAMAGE_RECEIVED] = new RibbonSettingByType(_loc3_,BATTLEATLAS.RIBBONS_DAMAGE_ENEMY,_loc4_,BATTLEATLAS.RIBBONS_DAMAGE_ENEMY_BLIND,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_NITRO_ACTIVATED] = new RibbonSettingByType(_loc2_,BATTLEATLAS.LS_NITRO_ACTIVATED,_loc2_,BATTLEATLAS.LS_NITRO_ACTIVATED,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_HEAL_SITUATIONAL] = new RibbonSettingByType(_loc2_,BATTLEATLAS.LS_HEAL_SITUATIONAL,_loc2_,BATTLEATLAS.LS_HEAL_SITUATIONAL,3);
         RIBBON_TYPES_MAP[LS_BATTLE_EFFICIENCY_TYPES.LS_EXTRA_DAMAGE_SITUATIONAL] = new RibbonSettingByType(_loc2_,BATTLEATLAS.LS_EXTRA_DAMAGE_SITUATIONAL,_loc2_,BATTLEATLAS.LS_EXTRA_DAMAGE_SITUATIONAL,3);
         DAMAGE_SOURCE_MAP[LS_DAMAGE_SOURCE_TYPES.ALPHA] = new DamageSourceSetting(BATTLEATLAS.LS_DAMAGE_LOG_ALPHA_16X16);
         DAMAGE_SOURCE_MAP[LS_DAMAGE_SOURCE_TYPES.BOMBER_ALPHA] = new DamageSourceSetting(BATTLEATLAS.LS_DAMAGE_LOG_BOMBER_ALPHA_16X16);
         DAMAGE_SOURCE_MAP[LS_DAMAGE_SOURCE_TYPES.BOMBER] = new DamageSourceSetting(BATTLEATLAS.LS_DAMAGE_LOG_BOMBER_16X16);
         DAMAGE_SOURCE_MAP[LS_DAMAGE_SOURCE_TYPES.HUNTER] = new DamageSourceSetting(BATTLEATLAS.LS_DAMAGE_LOG_HUNTER_16X16);
         DAMAGE_SOURCE_MAP[LS_DAMAGE_SOURCE_TYPES.RUNNER] = new DamageSourceSetting(BATTLEATLAS.LS_DAMAGE_LOG_RUNNER_16X16);
         DAMAGE_SOURCE_MAP[LS_DAMAGE_SOURCE_TYPES.SENTRY] = new DamageSourceSetting(BATTLEATLAS.LS_DAMAGE_LOG_SENTRY_16X16);
         DAMAGE_SOURCE_MAP[LS_DAMAGE_SOURCE_TYPES.TURRET] = new DamageSourceSetting(BATTLEATLAS.LS_DAMAGE_LOG_TURRET_16X16);
         DAMAGE_SOURCE_MAP[LS_DAMAGE_SOURCE_TYPES.CATCHER] = new DamageSourceSetting(BATTLEATLAS.LS_DAMAGE_LOG_CATCHER_16X16);
         DAMAGE_SOURCE_MAP[LS_DAMAGE_SOURCE_TYPES.CHARGER] = new DamageSourceSetting(BATTLEATLAS.LS_DAMAGE_LOG_CHARGER_16X16);
         DAMAGE_SOURCE_MAP[LS_DAMAGE_SOURCE_TYPES.RIPPER] = new DamageSourceSetting(BATTLEATLAS.LS_DAMAGE_LOG_RIPPER_16X16);
         DAMAGE_SOURCE_MAP[LS_DAMAGE_SOURCE_TYPES.DETONATOR] = new DamageSourceSetting(BATTLEATLAS.LS_DAMAGE_LOG_DETONATOR_16X16);
         DAMAGE_SOURCE_MAP[LS_DAMAGE_SOURCE_TYPES.BOSS] = new DamageSourceSetting(BATTLEATLAS.LS_DAMAGE_LOG_BOSS_16X16);
         ICON_X_PADDINGS[LS_DAMAGE_SOURCE_TYPES.ALPHA] = 0;
         ICON_Y_PADDINGS[LS_DAMAGE_SOURCE_TYPES.ALPHA] = 11;
         ICON_X_PADDINGS[LS_DAMAGE_SOURCE_TYPES.BOMBER_ALPHA] = 0;
         ICON_Y_PADDINGS[LS_DAMAGE_SOURCE_TYPES.BOMBER_ALPHA] = 11;
         ICON_X_PADDINGS[LS_DAMAGE_SOURCE_TYPES.BOMBER] = 0;
         ICON_Y_PADDINGS[LS_DAMAGE_SOURCE_TYPES.BOMBER] = 11;
         ICON_X_PADDINGS[LS_DAMAGE_SOURCE_TYPES.HUNTER] = 0;
         ICON_Y_PADDINGS[LS_DAMAGE_SOURCE_TYPES.HUNTER] = 11;
         ICON_X_PADDINGS[LS_DAMAGE_SOURCE_TYPES.RUNNER] = 0;
         ICON_Y_PADDINGS[LS_DAMAGE_SOURCE_TYPES.RUNNER] = 11;
         ICON_X_PADDINGS[LS_DAMAGE_SOURCE_TYPES.SENTRY] = 0;
         ICON_Y_PADDINGS[LS_DAMAGE_SOURCE_TYPES.SENTRY] = 11;
         ICON_X_PADDINGS[LS_DAMAGE_SOURCE_TYPES.TURRET] = 0;
         ICON_Y_PADDINGS[LS_DAMAGE_SOURCE_TYPES.TURRET] = 11;
         ICON_X_PADDINGS[LS_DAMAGE_SOURCE_TYPES.CATCHER] = 0;
         ICON_Y_PADDINGS[LS_DAMAGE_SOURCE_TYPES.CATCHER] = 11;
         ICON_X_PADDINGS[LS_DAMAGE_SOURCE_TYPES.CHARGER] = 0;
         ICON_Y_PADDINGS[LS_DAMAGE_SOURCE_TYPES.CHARGER] = 11;
         ICON_X_PADDINGS[LS_DAMAGE_SOURCE_TYPES.RIPPER] = 0;
         ICON_Y_PADDINGS[LS_DAMAGE_SOURCE_TYPES.RIPPER] = 11;
         ICON_X_PADDINGS[LS_DAMAGE_SOURCE_TYPES.DETONATOR] = 0;
         ICON_Y_PADDINGS[LS_DAMAGE_SOURCE_TYPES.DETONATOR] = 11;
         ICON_X_PADDINGS[LS_DAMAGE_SOURCE_TYPES.BOSS] = 0;
         ICON_Y_PADDINGS[LS_DAMAGE_SOURCE_TYPES.BOSS] = 11;
      }
   }
}

